# Generated by Django 4.1.5 on 2023-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='exit', upload_to='images'),
            preserve_default=False,
        ),
    ]
